# Generated by Django 4.2.23 on 2025-08-13 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=dict, verbose_name='Layout')),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='Theme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('list', 'List'), ('calendar', 'Calendar'), ('stats', 'Statistics'), ('custom', 'Custom')], max_length=20, verbose_name='Widget Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserWidgetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.PositiveSmallIntegerField(default=0, verbose_name='X Position')),
                ('position_y', models.PositiveSmallIntegerField(default=0, verbose_name='Y Position')),
                ('width', models.PositiveSmallIntegerField(default=1, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(default=1, verbose_name='Height')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_positions', to='dashboard.userpreference', verbose_name='User Preference')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_positions', to='dashboard.widget', verbose_name='Widget')),
            ],
            options={
                'verbose_name': 'Widget Position',
                'verbose_name_plural': 'Widget Positions',
                'ordering': ['position_y', 'position_x'],
                'unique_together': {('user_preference', 'widget')},
            },
        ),
        migrations.AddField(
            model_name='userpreference',
            name='widgets',
            field=models.ManyToManyField(related_name='user_preferences', through='dashboard.UserWidgetPosition', to='dashboard.widget', verbose_name='Widgets'),
        ),
    ]
