# Generated by Django 4.2.20 on 2025-06-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_logos/", verbose_name="Logo"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="registration_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Registration Number"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Company Code"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Company Name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
