# Generated by Django 4.2.23 on 2025-08-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Standard Code')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Standard',
                'verbose_name_plural': 'Standards',
                'ordering': ('category__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='StandardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Standard Category',
                'verbose_name_plural': 'Standard Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StandardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='standards/documents/', verbose_name='File')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Document Number')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='Version')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('obsolete', 'Obsolete')], default='draft', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_documents', to='accounts.customuser', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Standard Document',
                'verbose_name_plural': 'Standard Documents',
                'ordering': ['-uploaded_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StandardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('title', models.CharField(max_length=200, verbose_name='Section title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='standards.standardsection', verbose_name='Parent Section')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='standards.standard', verbose_name='Standard')),
            ],
            options={
                'verbose_name': 'Standard Section',
                'verbose_name_plural': 'Standard Sections',
                'ordering': ['standard', 'code', 'order'],
                'unique_together': {('standard', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StandardRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='update', max_length=20, verbose_name='Change Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('previous_value', models.TextField(blank=True, verbose_name='Previous Value')),
                ('new_value', models.TextField(blank=True, verbose_name='New Value')),
                ('diff', models.TextField(blank=True, verbose_name='Differences')),
                ('change_reason', models.TextField(blank=True, verbose_name='Change Reason')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_revisions', to='accounts.customuser', verbose_name='Changed By')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('standardsection', 'standardrequirement')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Standard Revision',
                'verbose_name_plural': 'Standard Revisions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StandardRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('text_original', models.TextField(verbose_name='Requirement Text (original)')),
                ('text_alt', models.TextField(verbose_name='Requirement Text (alternative)')),
                ('description_original', models.TextField(verbose_name='Description (original)')),
                ('description_alt', models.TextField(verbose_name='Description (alternative)')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='standards.standardsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Standard Requirement',
                'verbose_name_plural': 'Standard Requirements',
                'ordering': ['section', 'order', 'code'],
                'unique_together': {('section', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StandardCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('partial', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable'), ('in_progress', 'Implementation in Progress')], default='in_progress', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='standards.standardrequirement', verbose_name='Requirement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_records', to='accounts.customuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Standard Compliance',
                'verbose_name_plural': 'Standard Compliances',
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='StandardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='standards/attachments/', verbose_name='File')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_attachments', to='accounts.customuser', verbose_name='Created By')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='standards.standardsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Standard Attachment',
                'verbose_name_plural': 'Standard Attachments',
                'ordering': ['section', 'title'],
            },
        ),
        migrations.AddField(
            model_name='standard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='standards.standardcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='StandardDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('partial', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable'), ('in_progress', 'Implementation in Progress')], default='compliant', max_length=20, verbose_name='Compliance Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_standard_links', to='accounts.customuser', verbose_name='Created By')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_links', to='standards.standarddocument', verbose_name='Document')),
                ('standard_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='standards.standardsection', verbose_name='Standard Section')),
            ],
            options={
                'verbose_name': 'Standard-Document Link',
                'verbose_name_plural': 'Standard-Document Links',
                'ordering': ('standard_section__code', 'document__title'),
                'unique_together': {('standard_section', 'document')},
            },
        ),
    ]
