# Generated by Django 4.2.20 on 2025-06-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, verbose_name="Standard Number"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Standard Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "revision",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Revision"
                    ),
                ),
                (
                    "issuing_body",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Issuing Body",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Standard",
                "verbose_name_plural": "Standards",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="StandardSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="standards.standardsection",
                        verbose_name="Parent Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Section",
                "verbose_name_plural": "Standard Sections",
            },
        ),
        migrations.CreateModel(
            name="StandardSubsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subsection_number",
                    models.CharField(max_length=20, verbose_name="Subsection Number"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Subsection Title"),
                ),
                ("content", models.TextField(blank=True, verbose_name="Content")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections_new",
                        to="standards.standardsection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Subsection",
                "verbose_name_plural": "Standard Subsections",
                "ordering": ["section", "order", "subsection_number"],
            },
        ),
        migrations.CreateModel(
            name="StandardRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_number",
                    models.CharField(max_length=50, verbose_name="Revision Number"),
                ),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Revision",
                "verbose_name_plural": "Standard Revisions",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="StandardRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Is Mandatory"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Requirement",
                "verbose_name_plural": "Standard Requirements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StandardDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "file",
                    models.FileField(
                        upload_to="standards/documents/", verbose_name="File"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Document",
                "verbose_name_plural": "Standard Documents",
            },
        ),
        migrations.CreateModel(
            name="StandardAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="standards/attachments/", verbose_name="File"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Attachment",
                "verbose_name_plural": "Standard Attachments",
            },
        ),
    ]
