# Generated by Django 4.2.20 on 2025-06-26 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("standards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardrequirement",
            name="description",
        ),
        migrations.RemoveField(
            model_name="standardrequirement",
            name="text",
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="description_alt",
            field=models.TextField(
                default=django.utils.timezone.now,
                verbose_name="Description (alternative)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="description_original",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Description (original)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="text_alt",
            field=models.TextField(
                default=django.utils.timezone.now,
                verbose_name="Requirement Text (alternative)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="text_original",
            field=models.TextField(
                default=django.utils.timezone.now,
                verbose_name="Requirement Text (original)",
            ),
            preserve_default=False,
        ),
    ]
