# Generated by Django 4.2.20 on 2025-06-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("hire_date", models.DateField(verbose_name="Hire date")),
                ("employment_from", models.DateField(verbose_name="Employed from")),
                (
                    "employment_to",
                    models.DateField(blank=True, null=True, verbose_name="Employed to"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Currently employed"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.department",
                        verbose_name="Department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Field of expertise"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Position name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("lecture", "Lecture"),
                            ("research", "Research"),
                            ("publication", "Publication"),
                            ("congress", "Congress"),
                        ],
                        max_length=100,
                        verbose_name="Record type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Certificate",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="personnel.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="personnel.field",
                verbose_name="Field",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="personnel.position",
                verbose_name="Position",
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            (
                                "L1B",
                                "1st level professional higher education (college or short-cycle)",
                            ),
                            ("L2B", "2nd level professional or academic bachelor"),
                            ("AM", "Academic master’s degree"),
                            ("PM", "Professional master’s degree"),
                            ("DOC", "Doctoral degree (PhD)"),
                            ("MD", "Medical doctor"),
                        ],
                        max_length=3,
                        verbose_name="Education level",
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=200, verbose_name="Institution"),
                ),
                (
                    "graduation_year",
                    models.PositiveIntegerField(verbose_name="Graduation year"),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Field of study"
                    ),
                ),
                (
                    "diploma_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="education_certificates/",
                        verbose_name="Certificate or diploma",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="personnel.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
        ),
    ]
