# Generated by Django 4.2.20 on 2025-06-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_options_company_logo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualification_type",
                    models.CharField(max_length=100, verbose_name="Qualification Type"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("issue_date", models.DateField(verbose_name="Issue Date")),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                (
                    "issuing_organization",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Issuing Organization"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Certificate Number"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="qualification_documents/",
                        verbose_name="Document",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Qualification",
                "verbose_name_plural": "Qualifications",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "training_name",
                    models.CharField(max_length=255, verbose_name="Training Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Training Provider"
                    ),
                ),
                (
                    "certificate_issued",
                    models.BooleanField(
                        default=False, verbose_name="Certificate Issued"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Certificate Number"
                    ),
                ),
                (
                    "certificate_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Certificate Date"
                    ),
                ),
                (
                    "certificate_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="training_certificates/",
                        verbose_name="Certificate Document",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Training",
                "verbose_name_plural": "Training Records",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["-end_date", "-start_date"],
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AlterModelOptions(
            name="employeerecord",
            options={
                "ordering": ["-issue_date"],
                "verbose_name": "Employee Record",
                "verbose_name_plural": "Employee Records",
            },
        ),
        migrations.RemoveField(
            model_name="education",
            name="diploma_file",
        ),
        migrations.RemoveField(
            model_name="education",
            name="graduation_year",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="active",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employment_from",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employment_to",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="field",
        ),
        migrations.RemoveField(
            model_name="employeerecord",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="employeerecord",
            name="date",
        ),
        migrations.AddField(
            model_name="education",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="degree",
            field=models.CharField(blank=True, max_length=255, verbose_name="Degree"),
        ),
        migrations.AddField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="education",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="education_documents/",
                verbose_name="Diploma/Certificate",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AddField(
            model_name="education",
            name="is_completed",
            field=models.BooleanField(default=True, verbose_name="Completed"),
        ),
        migrations.AddField(
            model_name="education",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Start Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=50,
                unique=True,
                verbose_name="Employee ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="employee",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnel_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="employee_records/",
                verbose_name="Document",
            ),
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="is_confidential",
            field=models.BooleanField(default=False, verbose_name="Confidential"),
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Issue Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, verbose_name="Title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeerecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="education",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="personnel.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Field of Study"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(
                max_length=255, verbose_name="Educational Institution"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="level",
            field=models.CharField(
                choices=[
                    ("HIGH_SCHOOL", "High School"),
                    ("VOCATIONAL", "Vocational School"),
                    ("BACHELOR", "Bachelor's Degree"),
                    ("MASTER", "Master's Degree"),
                    ("DOCTORATE", "Doctorate"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                verbose_name="Education Level",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="company.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True, verbose_name="Hire Date"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                verbose_name="Position",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_records",
                to="personnel.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="employeerecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("CONTRACT", "Employment Contract"),
                    ("AGREEMENT", "Agreement"),
                    ("ASSESSMENT", "Performance Assessment"),
                    ("DISCIPLINARY", "Disciplinary Action"),
                    ("AWARD", "Award or Recognition"),
                    ("OTHER", "Other Document"),
                ],
                max_length=20,
                verbose_name="Record Type",
            ),
        ),
        migrations.DeleteModel(
            name="Field",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.AddField(
            model_name="training",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_records",
                to="personnel.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications",
                to="personnel.employee",
                verbose_name="Employee",
            ),
        ),
    ]
