# Generated by Django 4.2.20 on 2025-06-03 06:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Standard Number"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title in English"
                    ),
                ),
                (
                    "publication_year",
                    models.IntegerField(verbose_name="Publication Year"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Standard",
                "verbose_name_plural": "Standards",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="StandardSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Section Name")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Section Code"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Content")),
                (
                    "content_en",
                    models.TextField(blank=True, verbose_name="Content in English"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="standards.standardsection",
                        verbose_name="Parent Section",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Section",
                "verbose_name_plural": "Standard Sections",
                "unique_together": {("standard", "code")},
            },
        ),
        migrations.CreateModel(
            name="StandardSubsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Subsection Number"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title in English"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Content")),
                (
                    "content_en",
                    models.TextField(blank=True, verbose_name="Content in English"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="standards.standardsection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Subsection",
                "verbose_name_plural": "Standard Subsections",
                "ordering": ["order"],
                "unique_together": {("section", "number")},
            },
        ),
        migrations.CreateModel(
            name="StandardRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_number",
                    models.CharField(max_length=20, verbose_name="Revision Number"),
                ),
                ("revision_date", models.DateField(verbose_name="Revision Date")),
                (
                    "description",
                    models.TextField(verbose_name="Description of Changes"),
                ),
                (
                    "is_major",
                    models.BooleanField(default=False, verbose_name="Major Revision"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Revision",
                "verbose_name_plural": "Standard Revisions",
                "ordering": ["-revision_date"],
            },
        ),
        migrations.CreateModel(
            name="StandardRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement_id",
                    models.CharField(max_length=50, verbose_name="Requirement ID"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description in English"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Is Mandatory"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="standards.standardsection",
                        verbose_name="Section",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="standards.standardsubsection",
                        verbose_name="Subsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Requirement",
                "verbose_name_plural": "Standard Requirements",
                "ordering": ["requirement_id"],
            },
        ),
        migrations.CreateModel(
            name="StandardDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="Document Type"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="standards/documents/", verbose_name="Document File"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=20, verbose_name="Version"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Document",
                "verbose_name_plural": "Standard Documents",
            },
        ),
        migrations.CreateModel(
            name="StandardComplianceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("PARTIALLY", "Partially Compliant"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                            ("NOT_APPLICABLE", "Not Applicable"),
                            ("UNDER_REVIEW", "Under Review"),
                        ],
                        default="UNDER_REVIEW",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "evidence",
                    models.TextField(blank=True, verbose_name="Compliance Evidence"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "assessed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Assessment Date"
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Review Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_statuses",
                        to="standards.standardrequirement",
                        verbose_name="Requirement",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_statuses",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Compliance Status",
                "verbose_name_plural": "Standard Compliance Statuses",
                "ordering": ["-assessed_date"],
            },
        ),
        migrations.CreateModel(
            name="StandardAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("file", models.FileField(upload_to="standards/", verbose_name="File")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Attachment",
                "verbose_name_plural": "Standard Attachments",
            },
        ),
    ]
