# Generated by Django 4.2.20 on 2025-06-19 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Nosaukums")),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Dokumenta numurs"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("policy", "Politika"),
                            ("procedure", "Procedūra"),
                            ("instruction", "Instrukcija"),
                            ("form", "Veidlapa"),
                            ("other", "Cits"),
                        ],
                        max_length=20,
                        verbose_name="Dokumenta veids",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Melnraksts"),
                            ("review", "Pārskatīšanā"),
                            ("approved", "Apstiprināts"),
                            ("published", "Publicēts"),
                            ("archived", "Arhivēts"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statuss",
                    ),
                ),
                ("content", models.TextField(verbose_name="Saturs")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Izveidošanas datums"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atjaunināšanas datums"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Apstiprināšanas datums"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Versija"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/attachments/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Apstiprināja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Izveidoja",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Augšupielādēja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokuments",
                "verbose_name_plural": "Dokumenti",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_number",
                    models.CharField(max_length=20, verbose_name="Revision Number"),
                ),
                ("revision_date", models.DateField(verbose_name="Revision Date")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Current Revision"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Document Revision",
                "verbose_name_plural": "Document Revisions",
                "ordering": ["-revision_date"],
            },
        ),
        migrations.CreateModel(
            name="QualityDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Document Number"
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Version")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Quality Document",
                "verbose_name_plural": "Quality Documents",
                "ordering": ["document_number"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/attachments/", verbose_name="File"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="documents.document",
                        verbose_name="Dokuments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Attachment",
                "verbose_name_plural": "Document Attachments",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_number",
                    models.CharField(max_length=50, verbose_name="Section Number"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("content", models.TextField(blank=True, verbose_name="Content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Secība"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="documents.document",
                        verbose_name="Dokuments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumenta sadaļa",
                "verbose_name_plural": "Dokumenta sadaļas",
                "ordering": ["document", "order"],
                "unique_together": {("document", "order")},
            },
        ),
    ]
