# Generated by Django 4.2.20 on 2025-06-26 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentsection",
            options={
                "ordering": ["document", "parent__id", "order"],
                "verbose_name": "Document Section",
                "verbose_name_plural": "Document Sections",
            },
        ),
        migrations.AddField(
            model_name="documentsection",
            name="code",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=50,
                verbose_name="Section number",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentsection",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsections",
                to="documents.documentsection",
                verbose_name="Parent Section",
            ),
        ),
        migrations.AlterField(
            model_name="documentsection",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Section title"),
        ),
        migrations.AlterUniqueTogether(
            name="documentsection",
            unique_together={("document", "code")},
        ),
        migrations.RemoveField(
            model_name="documentsection",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="documentsection",
            name="updated_at",
        ),
    ]
