# Generated by Django 4.2.20 on 2025-06-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_add_uploaded_by_field"),
        ("documents", "0002_document_attachment_document_description_and_more"),
    ]

    operations = []
