# Generated by Django 4.2.20 on 2025-06-26 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_documentsection_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsection",
            name="content",
        ),
        migrations.RemoveField(
            model_name="documentsection",
            name="title",
        ),
        migrations.AddField(
            model_name="documentsection",
            name="content_alt",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Content (alternative)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentsection",
            name="content_original",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Content (original)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentsection",
            name="title_alt",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=200,
                verbose_name="Section title (alternative)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentsection",
            name="title_original",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=200,
                verbose_name="Section title (original)",
            ),
            preserve_default=False,
        ),
    ]
