# Generated by Django 4.2.20 on 2025-06-02 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Standard Number"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_secondary",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Title (Secondary Language)",
                    ),
                ),
                (
                    "publication_year",
                    models.PositiveIntegerField(verbose_name="Publication Year"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_secondary",
                    models.TextField(
                        blank=True, verbose_name="Description (Secondary Language)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("OBSOLETE", "Obsolete"),
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Under Review"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "issuing_body",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Issuing Body"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="standards/",
                        verbose_name="Standard Document",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_standards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard",
                "verbose_name_plural": "Standards",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="StandardSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(max_length=255, verbose_name="Title"),
                ),
                (
                    "section_title_secondary",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Title (Secondary Language)",
                    ),
                ),
                (
                    "section_number",
                    models.CharField(max_length=50, verbose_name="Section Number"),
                ),
                ("content", models.TextField(blank=True, verbose_name="Content")),
                (
                    "content_secondary",
                    models.TextField(
                        blank=True, verbose_name="Content (Secondary Language)"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Level"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Order")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="standards.standardsection",
                        verbose_name="Parent Section",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Section",
                "verbose_name_plural": "Standard Sections",
                "ordering": ["standard", "level", "order", "section_number"],
            },
        ),
        migrations.CreateModel(
            name="StandardSubsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_secondary",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Title (Secondary Language)",
                    ),
                ),
                (
                    "subsection_number",
                    models.CharField(max_length=50, verbose_name="Subsection Number"),
                ),
                ("content", models.TextField(blank=True, verbose_name="Content")),
                (
                    "content_secondary",
                    models.TextField(
                        blank=True, verbose_name="Content (Secondary Language)"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Level"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="standards.standardsubsection",
                        verbose_name="Parent Subsection",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="standards.standardsection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Subsection",
                "verbose_name_plural": "Standard Subsections",
                "ordering": ["section", "level", "order", "subsection_number"],
            },
        ),
        migrations.CreateModel(
            name="StandardRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement_id",
                    models.CharField(max_length=50, verbose_name="Requirement ID"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_secondary",
                    models.TextField(
                        blank=True, verbose_name="Description (Secondary Language)"
                    ),
                ),
                (
                    "compliance_criteria",
                    models.TextField(blank=True, verbose_name="Compliance Criteria"),
                ),
                (
                    "priority",
                    models.CharField(
                        default="MEDIUM", max_length=20, verbose_name="Priority"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements",
                        to="standards.standardsection",
                        verbose_name="Section",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements",
                        to="standards.standardsubsection",
                        verbose_name="Subsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Requirement",
                "verbose_name_plural": "Standard Requirements",
                "ordering": ["standard", "requirement_id"],
            },
        ),
        migrations.CreateModel(
            name="StandardDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="standard_documents/", verbose_name="File"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=100, verbose_name="Document Type"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="standards.standard",
                        verbose_name="Standard",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_standard_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Document",
                "verbose_name_plural": "Standard Documents",
            },
        ),
    ]
