# Generated by Django 4.2.23 on 2025-08-14 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Method Name')),
                ('identification', models.CharField(max_length=100, unique=True, verbose_name='Method Identification')),
                ('investigation_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Investigation Field')),
                ('analyzer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Analyzer/Equipment')),
                ('technology', models.TextField(blank=True, null=True, verbose_name='Investigation Technology')),
                ('test_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Test Material')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='Verification Date')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('internal_qc_required', models.BooleanField(default=True, verbose_name='Internal QC Required')),
                ('external_qc_required', models.BooleanField(default=True, verbose_name='External QC Required')),
                ('verification_required', models.BooleanField(default=True, verbose_name='Verification Required')),
                ('last_internal_qc_date', models.DateField(blank=True, null=True, verbose_name='Last Internal QC Date')),
                ('last_external_qc_date', models.DateField(blank=True, null=True, verbose_name='Last External QC Date')),
                ('next_verification_date', models.DateField(blank=True, null=True, verbose_name='Next Verification Date')),
                ('document', models.FileField(blank=True, null=True, upload_to='method_documents/', verbose_name='Method Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_methods', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Method',
                'verbose_name_plural': 'Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MethodInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MethodVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('verification', 'Verification'), ('validation', 'Validation'), ('revalidation', 'Revalidation')], default='verification', max_length=20, verbose_name='Verification Type')),
                ('verification_date', models.DateField(verbose_name='Verification Date')),
                ('performed_by', models.CharField(max_length=255, verbose_name='Performed By')),
                ('precision_data', models.TextField(blank=True, verbose_name='Precision Data')),
                ('accuracy_data', models.TextField(blank=True, verbose_name='Accuracy Data')),
                ('linearity_data', models.TextField(blank=True, verbose_name='Linearity Data')),
                ('detection_limit', models.CharField(blank=True, max_length=100, verbose_name='Detection Limit')),
                ('quantitation_limit', models.CharField(blank=True, max_length=100, verbose_name='Quantitation Limit')),
                ('acceptance_criteria', models.TextField(verbose_name='Acceptance Criteria')),
                ('results_summary', models.TextField(verbose_name='Results Summary')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_by', models.CharField(blank=True, max_length=255, verbose_name='Approved By')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('protocol_document', models.FileField(blank=True, upload_to='method_verification/protocols/', verbose_name='Protocol Document')),
                ('report_document', models.FileField(blank=True, upload_to='method_verification/reports/', verbose_name='Report Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='methods.method', verbose_name='Method')),
            ],
            options={
                'verbose_name': 'Method Verification',
                'verbose_name_plural': 'Method Verifications',
                'ordering': ['-verification_date'],
            },
        ),
        migrations.CreateModel(
            name='MethodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methods.methodinitial')),
            ],
        ),
        migrations.CreateModel(
            name='InternalQualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_date', models.DateField(verbose_name='Control Date')),
                ('control_material', models.CharField(max_length=255, verbose_name='Control Material')),
                ('control_lot', models.CharField(blank=True, max_length=100, verbose_name='Control Lot/Batch')),
                ('result', models.CharField(max_length=100, verbose_name='Result')),
                ('expected_value', models.CharField(max_length=100, verbose_name='Expected Value')),
                ('acceptable_range', models.CharField(blank=True, max_length=100, verbose_name='Acceptable Range')),
                ('is_conforming', models.BooleanField(default=True, verbose_name='Conforms to Expectations')),
                ('performed_by', models.CharField(max_length=255, verbose_name='Performed By')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_qc_records', to='methods.method', verbose_name='Method')),
            ],
            options={
                'verbose_name': 'Internal Quality Control',
                'verbose_name_plural': 'Internal Quality Controls',
                'ordering': ['-control_date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalQualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(max_length=255, verbose_name='Service Provider')),
                ('laboratory', models.CharField(max_length=255, verbose_name='Laboratory')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('test_material', models.CharField(max_length=255, verbose_name='Test Material')),
                ('technology_examination', models.CharField(max_length=255, verbose_name='Technology/Examination')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (€)')),
                ('test_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Test Amount (€)')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_quality_controls', to='methods.method', verbose_name='Method')),
            ],
            options={
                'verbose_name': 'External Quality Control',
                'verbose_name_plural': 'External Quality Controls',
                'ordering': ['service_provider', 'laboratory'],
            },
        ),
    ]
