name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # If you need a real Chrome+Xvfb service, you can run it here,
      # or install it later in the steps.
      xvfb:
        image: selenium/standalone-chrome:latest
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run migrations
        run: poetry run python manage.py migrate --no-input

      - name: Install ChromeDriver and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver xvfb

      - name: Run tests
        run: |
          xvfb-run -s "-screen 0 1920x1080x24" poetry run pytest

      - name: Lint with Flake8
        run: poetry run flake8 .

      - name: Type-check with Mypy
        run: poetry run mypy .

      - name: Black formatting check
        run: poetry run black --check .

      - name: isort import sorting check
        run: poetry run isort --check-only .

      - name: Generate coverage report
        run: |
          xvfb-run -s "-screen 0 1920x1080x24" poetry run pytest --cov=.
          coverage xml
        # you could upload artifacts here if desired
