name: CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  # —————————————————————————————
  # Existing test job (unit, lint, DB)
  # —————————————————————————————
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: quality_tools_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d quality_tools_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        run: |
          pytest
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/quality_tools_test

  # —————————————————————————————
  # New UI‐tests job (Selenium)
  # —————————————————————————————
  ui-tests:
    runs-on: ubuntu-latest
    needs: test   # wait for unit & lint to pass first

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Chrome, ChromeDriver & Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb chromium-browser chromium-chromedriver

      - name: Install Selenium & pytest
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pytest

      - name: Run Selenium UI tests
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' \
            pytest tests/test_ui.py --maxfail=1 --disable-warnings -q
